FROM python:3.11

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY ./pyproject.toml /app/pyproject.toml
RUN pip install .[worker]

COPY . /app

EXPOSE 8000
CMD python manage.py runserver 0.0.0.0:8000
