[project]
name = "ticker"
version = "0.0.1"
dependencies = [
    "Django==5.1.2",
    "django-environ==0.11.2",
    "psycopg2==2.9.10",
    "openpyxl==3.1.5",
    "procrastinate==2.15.0",
]

[project.optional-dependencies]
worker = ["yfinance==0.2.54"]

[tool.setuptools]
packages=[]
