# Generated by Django 5.1.2 on 2025-02-25 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickers', '0002_alter_ticker_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, verbose_name='number')),
                ('trading_date', models.DateField(verbose_name='trading date')),
                ('liquidation_date', models.DateField(verbose_name='liquidation date')),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='total value')),
                ('total_taxes', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='total taxes')),
                ('net_value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='net value')),
            ],
            options={
                'verbose_name': 'trading note',
                'verbose_name_plural': 'trading notes',
            },
        ),
        migrations.CreateModel(
            name='TradingStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='unit price')),
                ('trading_type', models.CharField(choices=[('BUY', 'buy'), ('SALE', 'sale')], default='BUY', verbose_name='trading type')),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickers.ticker', verbose_name='ticker')),
                ('trading_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='stocks.tradingnote', verbose_name='trading note')),
            ],
            options={
                'verbose_name': 'trading stock',
                'verbose_name_plural': 'trading stocks',
            },
        ),
    ]
