# Generated by Django 5.1.2 on 2025-02-25 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
            ],
            options={
                'verbose_name': 'tax',
                'verbose_name_plural': 'taxes',
            },
        ),
        migrations.CreateModel(
            name='TradingTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='value')),
                ('tax', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.tax', verbose_name='tax')),
                ('trading_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxes', to='stocks.tradingnote', verbose_name='trading note')),
            ],
            options={
                'verbose_name': 'trading tax',
                'verbose_name_plural': 'trading taxes',
            },
        ),
    ]
