# Generated by Django 5.1.2 on 2025-02-24 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_tax_tradingtax'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTimeSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('quantity', models.IntegerField(verbose_name='quantity')),
                ('buy_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='buy value')),
                ('cumulated_buy_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='cumulated buy value')),
                ('received_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='received value')),
                ('cumulated_received_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='cumulated received value')),
            ],
        ),
        migrations.AlterModelOptions(
            name='tradingnote',
            options={'ordering': ['-trading_date'], 'verbose_name': 'trading note', 'verbose_name_plural': 'trading notes'},
        ),
    ]
