# Generated by Django 5.1.2 on 2025-02-24 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_stocktimeseries_ticker'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stocktimeseries',
            options={'ordering': ['-date'], 'verbose_name': 'stock time series', 'verbose_name_plural': 'stock time series'},
        ),
        migrations.AddField(
            model_name='stocktimeseries',
            name='average_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='average cost'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stocktimeseries',
            name='cumulated_quantity',
            field=models.IntegerField(verbose_name='cumulated quantity'),
        ),
    ]
