# Generated by Django 5.1.2 on 2025-02-24 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('income', 'income'), ('dividend', 'dividend'), ('interest_on_equity', 'interest on equity')], max_length=20, verbose_name='event type')),
                ('quantity', models.IntegerField(verbose_name='quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='unit price')),
                ('net_value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='net value')),
                ('date', models.DateField(verbose_name='date')),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickers.ticker', verbose_name='ticker')),
            ],
            options={
                'verbose_name': 'payment event',
                'verbose_name_plural': 'payment events',
            },
        ),
    ]
