# Generated by Django 5.1.2 on 2025-02-24 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_events', '0001_initial'),
        ('tickers', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='paymentevent',
            constraint=models.UniqueConstraint(fields=('ticker', 'event_type', 'date'), name='unique_payment_event'),
        ),
    ]
