# Generated by Django 5.1.2 on 2025-02-25 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_events', '0002_paymentevent_unique_payment_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentevent',
            options={'ordering': ['-date'], 'verbose_name': 'payment event', 'verbose_name_plural': 'payment events'},
        ),
    ]
