# Generated by Django 5.1.2 on 2025-02-24 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='code')),
            ],
            options={
                'verbose_name': 'ticker',
                'verbose_name_plural': 'tickers',
            },
        ),
    ]
