# Generated by Django 5.1.2 on 2025-02-25 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticker',
            options={'ordering': ['code'], 'verbose_name': 'ticker', 'verbose_name_plural': 'tickers'},
        ),
    ]
