# Generated by Django 5.1.2 on 2025-03-01 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickers', '0002_alter_ticker_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TickerPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='date and time')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='tickers.ticker', verbose_name='ticker')),
            ],
        ),
    ]
