# Generated by Django 5.1.2 on 2025-03-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickers', '0003_tickerprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickerprice',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date and time'),
        ),
    ]
