# Generated by Django 5.1.2 on 2025-03-16 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickers', '0004_alter_tickerprice_date_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='TickerRename',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='code')),
                ('rename_to', models.CharField(max_length=10, verbose_name='code')),
            ],
            options={
                'verbose_name': 'ticker rename',
                'verbose_name_plural': 'tickers rename',
            },
        ),
    ]
